CREATE DEFINER=`root`@`localhost` FUNCTION `VALIDACION_CORREO`(CORREO2 varchar(250), CORREO1 VARCHAR(250)) RETURNS tinyint(20)
BEGIN
	DECLARE VALIDACION BOOL;
    
    IF CORREO2 = CORREO1 THEN
		SET VALIDACION = TRUE;
	ELSE
		SET VALIDACION = FALSE;
    END IF;
    
RETURN VALIDACION;
END