CREATE DATABASE TIENDAONLINE;
USE TIENDAONLINE;

CREATE TABLE USUARIOS(
    COD_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    CORREO VARCHAR(250) UNIQUE NOT NULL,
    PASS VARCHAR(100) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO1 VARCHAR(100) NOT NULL,
    APELLIDO2 VARCHAR(100),
    TELEFONO VARCHAR(100) NOT NULL,
    FNACI DATE NOT NULL
);

CREATE TABLE CATEGORIAS(
    COD_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    NOM_CATEGORIA VARCHAR(100),
    TIPOIVA DOUBLE
);

CREATE TABLE SUBCATEGORIAS(
    COD_SUBCATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    COD_CATEGORIA INT NOT NULL,
    NOM_SUBCATEGORIA VARCHAR(100),
    FOREIGN KEY (COD_CATEGORIA) REFERENCES CATEGORIAS(COD_CATEGORIA)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PRODUCTOS(
    COD_PRODUCTO INT PRIMARY KEY AUTO_INCREMENT,
    NOM_PRODUCTO VARCHAR(200) NOT NULL,
    MARCA VARCHAR(250) NOT NULL,
    MODELO VARCHAR(200) NOT NULL,
    DESC_PRODUCTO LONGTEXT,
    PRECIO DOUBLE NOT NULL,
    COD_CATEGORIA INT NOT NULL,
    FOREIGN KEY (COD_CATEGORIA) REFERENCES CATEGORIAS(COD_CATEGORIA)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PRODUCTOSFOTOS(
    COD_PRODUCTO INT NOT NULL,
    URL_FOTO VARCHAR(250) NOT NULL,
    DESC_FOTO VARCHAR(250),
    FOREIGN KEY (COD_PRODUCTO) REFERENCES PRODUCTOS(COD_PRODUCTO) 
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE COMPRAS(
    COD_COMPRA VARCHAR(30) ,
    COD_PRODUCTO INT NOT NULL,
    COD_USUARIO INT NOT NULL,
    CANTPRODUCTO INT NOT NULL,
    FCOMPRA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (COD_USUARIO) REFERENCES USUARIOS(COD_USUARIO)
    ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (COD_PRODUCTO) REFERENCES PRODUCTOS(COD_PRODUCTO)
    ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE COMPRAS;

DROP TABLE FACTURAS;

CREATE TABLE FACTURAS (
    COD_FACTURA INT PRIMARY KEY AUTO_INCREMENT,
    NUM_FACTURA VARCHAR(30),
    COD_COMPRA VARCHAR(30) NOT NULL,
    IMPORTE DOUBLE NOT NULL,
    FFACTURA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    COD_USUARIO INT NOT NULL,
    EMISOR VARCHAR(100)
);

DROP TABLE METODOPAGOS;

CREATE TABLE METODOPAGOS (
    COD_METODO INT PRIMARY KEY AUTO_INCREMENT,
	COD_FACTURA INT NOT NULL,
    METODO VARCHAR(100) NOT NULL,
    NUMERO_CARTA VARCHAR(16) NOT NULL,
    SCADENZA_CARTA DATE NOT NULL,
    TITOLARE_CARTA VARCHAR(200) NOT NULL,
    CVV VARCHAR(4) NOT NULL,
    FOREIGN KEY (COD_FACTURA) REFERENCES FACTURAS(COD_FACTURA)
    ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE ENVIOS;

CREATE TABLE ENVIOS(
    COD_ENVIOS INT PRIMARY KEY AUTO_INCREMENT,
    COD_USUARIO INT NOT NULL,
    DIRECCION VARCHAR(250) NOT NULL,
    CIUDAD VARCHAR(250) NOT NULL, 
    PROVINCIA VARCHAR(250) NOT NULL,
    PAIS VARCHAR(250) NOT NULL,
    CP VARCHAR(8) NOT NULL,
    COD_FACTURA INT NOT NULL,
    FENVIOS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FENTREGA DATE,
    ESTADO ENUM('GENERADO','EN_TRANSITO','ENTRAGADO'),
    FOREIGN KEY (COD_USUARIO) REFERENCES USUARIOS(COD_USUARIO)
    ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (COD_FACTURA) REFERENCES FACTURAS(COD_FACTURA)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CARRITOS(
    COD_USUARIO INT NOT NULL,
    COD_PRODUCTO INT NOT NULL,
    CANTPRODUCTO INT NOT NULL,
    FOREIGN KEY (COD_USUARIO) REFERENCES USUARIOS(COD_USUARIO)
    ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (COD_PRODUCTO) REFERENCES PRODUCTOS(COD_PRODUCTO)
    ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO USUARIOS (CORREO, PASS, NOMBRE, APELLIDO1, APELLIDO2, TELEFONO, FNACI) 
VALUES 
('usuario1@example.com', 'password1', 'Nombre1', 'Apellido1_1', 'Apellido1_2', '123456789', '1990-01-01'),
('usuario2@example.com', 'password2', 'Nombre2', 'Apellido2_1', 'Apellido2_2', '987654321', '1995-02-15'),
('usuario3@example.com', 'password3', 'Nombre3', 'Apellido3_1', 'Apellido3_2', '456789123', '1985-05-10');


INSERT INTO PRODUCTOS (NOM_PRODUCTO, MARCA, MODELO, DESC_PRODUCTO, PRECIO, COD_CATEGORIA) 
VALUES 
('Producto 1', 'Marca 1', 'Modelo 1', 'Descripción del producto 1', 50.00, 1),
('Producto 2', 'Marca 2', 'Modelo 2', 'Descripción del producto 2', 75.00, 2),
('Producto 3', 'Marca 3', 'Modelo 3', 'Descripción del producto 3', 100.00, 3);


INSERT INTO CATEGORIAS (NOM_CATEGORIA, TIPOIVA) 
VALUES 
('Electrónica', 0.21),
('Ropa', 0.16),
('Alimentación', 0.10);

SELECT GENERA_ID_COMPRA(1,2);

DROP TABLE PRODUCTOS;

SELECT * FROM PRODUCTOS;
INSERT INTO CARRITOS (COD_USUARIO,COD_PRODUCTO, CANTPRODUCTO) VALUES 
(3,4,2),
(3,5,3),
(3,6,1);


/*
funciones
CREATE DEFINER=`root`@`localhost` FUNCTION `CALCULA_IMPORTE`(CODIGO_COMPRA VARCHAR(30)) RETURNS double
BEGIN
	DECLARE IMPORTE DOUBLE;
    DECLARE CODIGO VARCHAR(30);
    
    SET IMPORTE = 0;
    
    SET CODIGO = CODIGO_COMPRA;
    
    SET IMPORTE = (SELECT SUM(PRECIO*CANTPRODUCTO) FROM COMPRAS INNER JOIN PRODUCTOS ON COMPRAS.COD_PRODUCTO = PRODUCTOS.COD_PRODUCTO WHERE COMPRAS.COD_COMPRA = CODIGO);
    
RETURN IMPORTE;
END


CREATE DEFINER=`root`@`localhost` FUNCTION `GENERA_ID_COMPRA`(COD_USUARIO INT  ) RETURNS varchar(30) CHARSET utf8mb4 COLLATE utf8mb4_general_ci
BEGIN
    DECLARE TIEMPO  TIMESTAMP;
    DECLARE CODIGO VARCHAR(30);
    DECLARE NOMBRE_AUX VARCHAR(100);
    DECLARE APELLIDO VARCHAR(100);
    DECLARE RESULTADO VARCHAR(30);
    
    SET TIEMPO = CURRENT_TIMESTAMP();
    
    SET NOMBRE_AUX = (SELECT NOMBRE FROM USUARIOS WHERE USUARIOS.COD_USUARIO = COD_USUARIO);
    
    SET APELLIDO = (SELECT APELLIDO1 FROM USUARIOS WHERE USUARIOS.COD_USUARIO = COD_USUARIO);
    
    SET RESULTADO = CONCAT_WS('-', COD_USUARIO, DAY(TIEMPO), HOUR(TIEMPO), MINUTE(TIEMPO), SECOND(TIEMPO), CONCAT(YEAR(TIEMPO), MONTH(TIEMPO)));
    
    RETURN RESULTADO;
END


CREATE DEFINER=`root`@`localhost` FUNCTION `CALCULA_IMPORTE`(CODIGO_COMPRA VARCHAR(30)) RETURNS double
BEGIN
	DECLARE IMPORTE DOUBLE;
    DECLARE CODIGO VARCHAR(30);
    
    SET IMPORTE = 0;
    
    SET CODIGO = CODIGO_COMPRA;
    
    SET IMPORTE = (SELECT SUM(PRECIO*CANTPRODUCTO) FROM COMPRAS INNER JOIN PRODUCTOS ON COMPRAS.COD_PRODUCTO = PRODUCTOS.COD_PRODUCTO WHERE COMPRAS.COD_COMPRA = CODIGO);
    
RETURN IMPORTE;
END


procedimientos


CREATE DEFINER=`root`@`localhost` PROCEDURE `GENERATE_FACTURA`(CODIGO_COMPRA VARCHAR(30))
BEGIN
	
    DECLARE NUM_FACTURA_AUX VARCHAR(30);
    DECLARE importe_total DOUBLE;
    DECLARE COD_USUARIO_AUX INT;
    DECLARE EMISOR_AUX VARCHAR(50);
    
    SET COD_USUARIO_AUX = (SELECT COD_USUARIO FROM COMPRAS WHERE COD_COMPRA = CODIGO_COMPRA LIMIT 1);
    
    SET importe_total = CALCULA_IMPORTE(codigo_compra);
    
    SET EMISOR_AUX = 'FONDO NORTE';
    SET NUM_FACTURA_AUX = (SELECT MAX(COD_FACTURA)+1 FROM FACTURAS);
    
    SET NUM_FACTURA_AUX = CONCAT(NUM_FACTURA_AUX,"/",YEAR(NOW()));
    
    INSERT INTO FACTURAS (NUM_FACTURA, COD_COMPRA, IMPORTE, FFACTURA, COD_USUARIO, EMISOR)
    VALUES (NUM_FACTURA_AUX, codigo_compra, importe_total, CURRENT_TIMESTAMP(), COD_USUARIO_AUX, EMISOR_AUX);
    
END


CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERTAR_COMPRA`(US INT )
BEGIN
	DECLARE CODIGO VARCHAR(30);
    DECLARE CONTADOR INTEGER;
    DECLARE MAX_FILAS INTEGER;
    DECLARE CODIGO_USUARIO INTEGER;
    DECLARE CODIGO_PRODUCTO INTEGER;
    DECLARE CANTIDAD_AUX INTEGER;
    DECLARE FECHACOMPRA TIMESTAMP;
    DECLARE IMPORTE_AUX DOUBLE;
    DECLARE PRECIO DOUBLE;
    
    SET FECHACOMPRA = CURRENT_TIMESTAMP();
    SET CODIGO = (SELECT GENERA_ID_COMPRA(US));
    SET CODIGO_USUARIO = US;
    SET IMPORTE_AUX = 0;
    
    SET CONTADOR = (SELECT COUNT(*) FROM CARRITOS WHERE COD_USUARIO = CODIGO_USUARIO);
    
    
    WHILE CONTADOR > 0 DO 
        SET CODIGO_PRODUCTO = (SELECT COD_PRODUCTO FROM CARRITOS WHERE COD_USUARIO = CODIGO_USUARIO ORDER BY COD_PRODUCTO LIMIT 1);
        SET CANTIDAD_AUX = (SELECT CANTPRODUCTO FROM CARRITOS WHERE COD_USUARIO = CODIGO_USUARIO ORDER BY COD_PRODUCTO LIMIT 1);
        
        SET PRECIO = (SELECT PRECIO FROM PRODUCTOS WHERE COD_PRODUCTO = CODIGO_PRODUCTO);
        
        INSERT INTO COMPRAS (COD_COMPRA, COD_PRODUCTO, COD_USUARIO, CANTPRODUCTO) VALUES
        (CODIGO,CODIGO_PRODUCTO,CODIGO_USUARIO,CANTIDAD_AUX);
        
        DELETE FROM CARRITOS WHERE COD_USUARIO = US AND COD_PRODUCTO = CODIGO_PRODUCTO;
        
        SET CONTADOR = CONTADOR - 1;
    END WHILE;
    
    SET IMPORTE_AUX = (SELECT SUM(PRECIO*CANTPRODUCTO) FROM COMPRAS INNER JOIN PRODUCTOS ON COMPRAS.COD_PRODUCTO = PRODUCTOS.COD_PRODUCTO WHERE COMPRAS.COD_COMPRA = CODIGO);
    SELECT IMPORTE_AUX;
    
END


*/